[package]
name = "hpc-otel-exporter"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1.0.101"
crossbeam-channel = "0.5.16"
dashmap = { version = "6.1.0", features = ["inline"] }
env_logger = "0.11"
libbpf-rs = "0.27.0"
libbpf-sys = "1.6.3"
libc = "0.2"
log = "0.4"
opentelemetry = { version = "0.32", features = ["metrics", "trace", "logs"] }
opentelemetry-otlp = { version = "0.32", default-features = false, features = [
    "metrics",
    "trace",
    "logs",
    "internal-logs",
    "grpc-tonic",
    "zstd-tonic",
    "tls-roots",
    "tls-aws-lc",
] }
opentelemetry_sdk = { version = "0.32", features = [
    "metrics",
    "trace",
    "logs",
    "experimental_metrics_bound_instruments",
    "experimental_metrics_custom_reader",
] }
opentelemetry-appender-log = "0.32"
tracing-opentelemetry = "0.33.0"
rustc-hash = "2"
tokio = { version = "1.48", features = ["full"] }
tokio-util = { version = "0.7", features = ["rt"] }
pyroscope = { version = "2.0.3", features = [
    "backend-pprof-rs",
], optional = true }
clap = { version = "4.6.1", features = ["derive"] }
blazesym = { version = "0.2.5", features = ["xz", "zstd", "tracing"] }
prost = "0.14.3"
reqwest = { version = "0.13", default-features = false, features = [
    "rustls",
    "gzip",
] }
flate2 = "1"
uuid = { version = "1", features = ["v7"] }
lru = "0.18.0"
gimli = { version = "0.33", default-features = false, features = [
    "read",
    "std",
] }
object = { version = "0.40", default-features = false, features = [
    "read",
    "std",
] }
memmap2 = "0.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tcmalloc-better = { version = "0.1.19", optional = true }
nix = { version = "0.31.3", features = [
    "user",
    "fs",
], default-features = false }
landlock = "0.4.5"

[patch.crates-io]
gimli = { git = "https://github.com/Jannik2099/gimli.git", rev = "b6a29d5900886ac11a63686e5af5d1031406225b" }

[features]
default = ["tcmalloc"]

pyroscope = ["dep:pyroscope"]
tcmalloc = ["dep:tcmalloc-better"]

[build-dependencies]
libbpf-cargo = "0.27.0"
serde_json = "1.0.149"
bindgen = "0.72.1"
prost-build = "0.14.3"
protoc-bin-vendored = "3.2.0"

[profile.release]
lto = "thin"
opt-level = 3
debug = "line-tables-only"
