[Match]
Distribution=rocky

[Content]
Packages=
    elfutils-libelf
    zlib
    libzstd
    libstdc++
    ca-certificates
BuildPackages=
    elfutils-libelf-devel
    zlib-devel
    libzstd-devel
    clang
    curl
    bash
