//! Protobuf message types generated by `prost` at build time (see build.rs),
//! used by the profiler's output path: pprof for the profile body and the
//! Pyroscope push API for the upload envelope.

/// Generated from `profile.proto` (pprof, package `google.v1`).
pub mod pprof {
    #![allow(warnings)]
    include!(concat!(env!("OUT_DIR"), "/google.v1.rs"));
}

/// Generated from `pyroscope_push.proto` (Pyroscope push API, package `push.v1`).
pub mod push {
    #![allow(warnings)]
    include!(concat!(env!("OUT_DIR"), "/push.v1.rs"));
}
