//! Rust view of the types shared with the eBPF programs.
//!
//! Generated by bindgen from `src/bpf/shared.h` (which aggregates the per-feature
//! `io.h` / `profiling.h`) at build time; see build.rs. Feature-specific inherent
//! impls on these types live with the feature (e.g. `FsMagic` helpers in
//! [`crate::metrics::io`]).
#![allow(warnings)]
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
